#!/bin/sh
set -eu

PROJECT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
if [ "$#" -ne 1 ] || [ ! -d "$1/Casks" ]; then
    printf '%s\n' 'Usage: scripts/update-cask.sh /path/to/homebrew-tap' >&2
    exit 2
fi
VERSION=$(sed -n 's/.*static let current = "\([^"]*\)".*/\1/p' "$PROJECT_DIR/Sources/DisplayRememberCore/Version.swift")
case "$VERSION" in ''|*[!0-9.]*) printf '%s\n' 'Invalid release version.' >&2; exit 2 ;; esac
ARCHIVE="$PROJECT_DIR/dist/display-remember-$VERSION-arm64.zip"
test -f "$ARCHIVE" && test -r "$ARCHIVE" || { printf '%s\n' 'Build the arm64 release ZIP before updating the cask.' >&2; exit 2; }
CHECKSUM_OUTPUT=$(shasum -a 256 "$ARCHIVE")
CHECKSUM=${CHECKSUM_OUTPUT%% *}
if ! printf '%s\n' "$CHECKSUM" | grep -Eq '^[0-9a-f]{64}$'; then
    printf '%s\n' 'Could not calculate a valid SHA-256 checksum.' >&2
    exit 2
fi
CASK_STAGING=$(mktemp "$1/Casks/.display-remember.XXXXXX")
trap 'rm -f "$CASK_STAGING"' EXIT HUP INT TERM
cat > "$CASK_STAGING" <<EOF
# Generated by scripts/update-cask.sh in d0lim/display-remember.
cask "display-remember" do
  version "$VERSION"
  sha256 "$CHECKSUM"

  url "https://github.com/d0lim/display-remember/releases/download/v#{version}/display-remember-#{version}-arm64.zip"
  name "Display Remember"
  desc "Remember physical monitors and restore their layouts"
  homepage "https://github.com/d0lim/display-remember"

  depends_on arch: :arm64
  depends_on macos: :ventura

  app "Display Remember.app"
  binary "#{appdir}/Display Remember.app/Contents/MacOS/display-remember"

  zap trash: [
    "~/Library/Application Support/display-remember",
    "~/Library/Preferences/dev.d0lim.display-remember.plist",
    "~/Library/Saved Application State/dev.d0lim.display-remember.savedState",
  ]
end
EOF
mv -f "$CASK_STAGING" "$1/Casks/display-remember.rb"
printf '%s\n' "$1/Casks/display-remember.rb"
